apiVersion: apps/v1
kind: Deployment
metadata:
  name: workercontagem
spec:
  selector:
    matchLabels:
      app: workercontagem
  replicas: 1
  template:
    metadata:
      labels:
        app: workercontagem
    spec:
      containers:
      - name: workercontagem
        image: renatogroffe/workercontagem-dotnet7-azurequeuestorage:1
        env:
        - name: AzureQueueStorage__Queue
          value: queue-testes
        - name: ConnectionStrings__ApplicationInsights
          valueFrom:
            secretKeyRef:
              name: workercontagemsecret
              key: ConnectionAppInsights
        - name: ConnectionStrings__AzureQueueStorage
          valueFrom:
            secretKeyRef:
              name: workercontagemsecret
              key: ConnectionAzureStorage
        - name: ConnectionStrings__BaseContagem
          valueFrom:
            secretKeyRef:
              name: workercontagemsecret
              key: ConnectionSqlServer