apiVersion: v1
kind: Secret
metadata:
  name: workercontagemsecret
type: Opaque
data:
  ConnectionAppInsights: <STRING DE CONEXÃO PARA DO APPLICATION INSIGHTS EM BASE 64>
  ConnectionAzureStorage: <STRING DE CONEXÃO PARA DO AZURE QUEUE STORAGE EM BASE 64>
  ConnectionSqlServer: <STRING DE CONEXÃO DO SQL SERVER EM BASE 64>